name: my_douban
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: ^0.16.0
  provider: ^4.0.1
  json_annotation: ^3.0.1

  http_parser: ^3.1.3

  dio: ^3.0.8
  dio_cookie_manager: ^1.0.0

  camera: ^0.5.6+3
  path_provider: ^1.4.4
  shared_preferences: ^0.5.4+3

  fluttertoast: ^2.1.1
  cached_network_image: ^2.0.0
  video_player: 0.10.0+4
  
  oktoast: ^2.3.2
  mobx_codegen: ^1.1.0+1


  validators:
  hnpwa_client:
  url_launcher:


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.0
  json_serializable: ^3.2.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
 
  uses-material-design: true
  assets:
    - assets/images/
 